{% set name = "types-unopy" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6561f9d25d7601d9494eed376c4dfeee0e3f6f40c4d0ecd7d11950cb0405979e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - types-uno-script >=0.1.0
    - typing-extensions >=3.7.4.3

test:
  imports:
    - com
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Amourspirit/python-types-unopy
  summary: Type annotations for LibreOffice API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Amourspirit
