{% set name = "types-unopy" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-unopy-{{ version }}.tar.gz
  sha256: 43e71d2a8fcf87638a6ca54465ba6ff7456a892d805dfde0c4aab9b1df8e8c71

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - types-uno-script >=0.1.0
    - typing-extensions >=3.7.4.3

test:
  imports:
    - com
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Amourspirit/python-types-unopy
  summary: Type annotations for LibreOffice API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Amourspirit
